README.md, docs/features.md, install/playbooks/luks-remote.yml, install/playbooks/main.yml, install/playbooks/roles/luks-remote/tasks/main.yml
Unlock the system through SSH when it boots, using an embedded dropbear server.
The SSH public keys are shared with the OpenSSH server, which avoids SSH warnings on login.
=> Unlock the system through SSH when it boots.

install/playbooks/roles/dns-server-bind-refresh/tasks/main.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/reverse-domain, tests/playbooks/roles/autodiscover/tasks/main.yml
- fixed backup IP address when IPv6 / IPv4 mix
- refresh DNS cache when assembling DNS entries
=> DNS: bind9 server IPv6 / IPv4 fixes

config/defaults.yml, docs/email-configuration.md, install/playbooks/roles/dovecot/defaults/main.yml, install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/dovecot/templates/conf.d/10-auth.conf, install/playbooks/roles/dovecot/templates/conf.d/10-ssl.conf, install/playbooks/roles/dovecot/templates/conf.d/15-lda.conf, install/playbooks/roles/dovecot/templates/conf.d/90-plugin.conf, install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext, install/playbooks/roles/luks-remote/tasks/set-dropbear.yml, install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/apparmor.d/usr.sbin.postalias, install/playbooks/roles/postfix/templates/main.cf, install/playbooks/roles/roundcube/templates/config.inc.php, install/playbooks/roles/rspamd/tasks/main.yml
Do not use the backports repository for dovecot
Postfix updates: added postalias AppArmor profile
Do not copy messages in the sent folder with Roundcube
Small fix on dropbear role
Updated email documentation.
Quota service fix with mail extensions and unicode email addresses
- Remove email aliases from user and pass LDAP filters.
- Remove quotes from the recipient delimitier list.
options.
- Fix authentication username characters according to the deploymen
Dovecot fixes
- Add comments in the configuration file
- Move mail quota milter to last position
- Removed NIS warnings
postfix improvements and small fixes
Email configuration documentation updates
Removed Ansible apt loop on rspamd
=> more fixes ready to dev

config/defaults.yml, config/system-example.yml, install/playbooks/roles/remote-access/tasks/main.yml, install/playbooks/roles/system-cleanup/handlers/main.yml, install/playbooks/roles/system-cleanup/tasks/main.yml
This can be used to disable root login at all, if this is is the favoured remote access method.
=> Allow some users to use sudo and SSH access to administer the system

install/playbooks/roles/dovecot/templates/conf.d/10-master.conf
access logging has now its dedicated structure, access_check
=> Changed macro in dovecot configuration

config/defaults.yml, config/system-example.yml, docs/backup-home.md, docs/backup-restore.md, install/playbooks/borgbackup.yml, install/playbooks/roles/borg-backup/files/backup.py, install/playbooks/roles/borg-backup/tasks/install-protocol-cifs.yml, install/playbooks/roles/borg-backup/tasks/install-protocol-s3fs.yml, install/playbooks/roles/borg-backup/tasks/main.yml, install/playbooks/roles/borg-backup/tasks/restore-all.yml, install/playbooks/roles/borg-backup/templates/cron-backup-script.sh, install/playbooks/roles/borg-backup/templates/cron-check-script.sh, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/extra-records.conf, install/playbooks/roles/system-prepare/tasks/main.yml, install/playbooks/roles/system-prepare/templates/bashrc
- Import / Export keys on repository creation
- Factorise subprocess.run
- Check if a repository has a key before importing one
- Add the configuration name as a suffix by default to the name of the
- log file
- CIFS: Add output firewall rules
- Allow rate limit
- Use weekly repository check by default
=> Backup and restore improvements

install/playbooks/roles/packages/templates/sources.list, install/playbooks/roles/rspamd/handlers/main.yml, install/playbooks/roles/rspamd/tasks/main.yml
- Use deb.debian.org (httpredir not maintained any more)
- Use Debian backports for rspamd
=> Default packages repository update

install/playbooks/roles/borg-backup/tasks/main.yml, install/playbooks/roles/borg-backup/tasks/restore-all.yml, install/playbooks/roles/borg-backup/templates/cron-backup-script.sh, install/playbooks/roles/borg-backup/templates/cron-check-script.sh
This should avoid clashes with other binaries called ‘backup’ on Debian.
=> Use a custom name for the backup and restore script

install/playbooks/roles/system-prepare/tasks/main.yml
This should hopefully fix the random issues on packages repository updates with vultr
=> Wait for the dpkg file to be unlocked before the first update

install/playbooks/roles/borg-backup/tasks/main.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/packages/tasks/main.yml, install/playbooks/roles/packages/templates/sources.list, preseed/Dockerfile
A few changes now that stretch is oldstable.
Concerns the apt source.list and backports, the preseed docker base image, and a change in apticron configuration handling in buster.
=> Debian releases specifics

install/playbooks/roles/remote-access/tasks/ufw-rules.yml
Remove the dependency of curl on the ansible host. The user running
ansible-playbook might not have the right to install software, nor to
have apt mark it as manually installed if already present.
=> Use the uri module to get external IP addresses

install/playbooks/roles/system-cleanup/tasks/network-bind.yml, install/playbooks/roles/system-cleanup/templates/dhclient.conf, install/playbooks/roles/system-cleanup/templates/homebox-dhclient-hook.sh, install/playbooks/roles/system-cleanup/templates/resolv.conf
Use the default list of requested options from the Debian package and
use prepend and supersede modifiers. The modifiers are only used if the
corresponding option is received via DHCP.
- Prepend for domain-name-servers and dhcp6.name-servers.
Allows to use localhost but also have the network configured DNS
server as backup in case bind is down.
- Supersede for domain-search, domain-name, host-name,
dhcp6.name-servers and dhcp6.domain-search.
Allows to ignore these network sent parameters, eg. we do not want to
have the dhclient-script overwriting our hostname.
The configured domain is network.domain, the configured hostname is
deduced from the first part of network.hostname.
Remove the homebox-dhclient-hook.sh.
=> Use dhclient options to handle /etc/resolv.conf

config/defaults.yml, install/playbooks/roles/remote-access/tasks/main.yml
Force SSH authentication to use public / private key for all users if
security.ssh_disable_users_access_with_password is true.
Configured during remote access setup.
The default value is set to false.
=> Add ssh_disable_users_access_with_password option

config/defaults.yml, install/playbooks/roles/dns-server-bind/templates/forward-head, install/playbooks/roles/dns-server-bind/templates/named.conf.options
Disallow zone transfers by default in bind.
Allow for configuration of secondary servers: NS records and allow-transfer match entries by IP address.
=> Allow configuration of secondary nameservers

install/playbooks/roles/certificates/templates/nginx-cert.conf
This would have affected dev branch only, but pretty annoying.
I should remember, from now on, the Ansible / Python way to test for None, empty strings, etc.
=> Fixed wrong nginx template when certificate has no alias

install/playbooks/roles/system-prepare/tasks/main.yml
Remove dependency on fuser.
The minimal image I am installing on does not have fuser :sweat_smile:
=> Determine dpkg lock with ls

install/playbooks/roles/system-cleanup/templates/dhclient.conf
The "splitext" filter is for filenames and file extensions.
The "split" function is more generic.
=> Fix the hostname short name in dhclient.conf

install/playbooks/roles/certificates/tasks/gencert.yml
Avoid certificates getting a domain_alias from a previous run of the
certificate role.
Move certificate specific variables from playbook variables to role
parameters. Role parameters take precedence over facts set during
previous runs of the same role with different parameters ([Variable
precedence]).
If the domain_alias is not specified as a role parameter, the
certificate role will use the domain_alias fact set during gencert.yml
by the previous certificate role using one (eg. smtp2 from
cert-smtp.yml).
Configure "domain_alias: ~" in every playbook not using a domain_alias
for the requested certificates.
[Variable precedence]: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
=> Default domain_alias to undefined for certificates

install/playbooks/roles/autoconfig/templates/config-v1.1.xml, install/playbooks/roles/autodiscover/templates/autodiscover.xml, install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/dovecot/templates/40-dovecot.bind, install/playbooks/roles/dovecot/templates/conf.d/10-master.conf, tests/playbooks/mail-certificates.yml
Following e8e3d2a, the POP3 services were not really disabled. If the `dovecot-pop3d` packages is installed, it seems inet listeners with `port=0` are required to disable the services (see commit description).
Also take care of the firewall rules configuration.
There is a newline added in the `40-dovecot.bind` file. I will propose a change to add missing newlines at end of files, but if you can merge this one first that would be great.
=> POP3 disabled by default

install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/mailname, install/playbooks/roles/postfix/templates/main.cf, install/playbooks/roles/postfix/templates/master.cf, install/playbooks/roles/sogo/templates/sogo.conf, tests/playbooks/roles/clamav/tasks/main.yml, tests/playbooks/roles/dev-support/defaults/main.yml, tests/playbooks/roles/dovecot-fts/tasks/send-attachment.yml, tests/playbooks/roles/postfix/tasks/check-extension-email.yml, tests/playbooks/roles/postfix/tasks/check-simple-email.yml, tests/playbooks/roles/postfix/tasks/check-utf8-email.yml
Some changes in the Postfix configuration concerning myhostname, the (unused) debian specific `/etc/mailname`, the `ETRN` command, TLS and authentication.
This does not changes the `*_restrictions` parameters. Maybe the submission ports configuration could later be made more restrictive? (Like `smtpd_tls_security_level=encrypt` if the SOGo configuration can be dealt with, and restrict submission to `sasl_authenticated` only?)
=> Postfix configuration

common/roles/external-ip-type/tasks/main.yml, install/playbooks/roles/dns-server-bind-refresh/tasks/main.yml, install/playbooks/roles/dns-server-bind/tasks/build-ip-info.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-check-propagation/tasks/main.yml, install/playbooks/roles/dovecot/templates/40-dovecot.bind, install/playbooks/roles/ejabberd/templates/50-jabber.bind, install/playbooks/roles/mta-sts/templates/mta-sts.txt
Use 'backup_ip is defined and backup_ip != ""' everywhere. It is already
used in the dns-server-bind playbook.
The external-ip-type common playbook sets the backup_ip fact to the
empty string if `network.auto_detect_ip` is false and
`network.backup_ip` is null, or if `network.auto_detect_ip` is true and
the obtained `backup_ip` is different from the external_ip.
The checks cannot reliably be made on `network.backup_ip`.
Use `backup_ip` instead of `network.backup_ip` where relevant.
=> Let backup_ip checks be coherent

config/system-example.yml, docs/backup-home.md, install/playbooks/roles/borg-backup/tasks/install-protocol-dir.yml
Use dir:///var/backups/homebox for the location to be the absolute path
/var/backups/homebox when processed by backup.py.
=> Fix dir backup urls examples

install/playbooks/roles/ldap/tasks/main.yml
This must not be used very often. During the ldap setup, the task is only called when the `clean` variable is set to remove the postmaster account before creating it again.
=> Fix the removal of the postmaster account

install/playbooks/roles/ldap/variables/main.yml, install/playbooks/roles/user-setup/tasks/main.yml, install/playbooks/user-setup.yml, tests/playbooks/roles/ldap/tasks/main.yml
Modify the tasks in the `user_setup.yml`.
- First, add files to /etc/skel.
- Then, use PAM's mkhomedir_helper to create home directories. It uses the
primary user group for the files creation, so force the home directories
to be set to the group "users".
- Doing so, copy bash related and .profile files to home directories.
Give users a bash shell by default.
=> Simplify home directories creation

config/defaults.yml, install/playbooks/roles/dns-server-bind-refresh/tasks/main.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/named.conf.local, install/playbooks/roles/dns-server-bind/templates/reverse-domain
These commits modify the reverse DNS zones generation and add an boolean option to generate or not the zones.
- Announce the nameserver in the SOA.
- Announce the backup nameserver if available.
- Use the full reverse IP address for the PTR record.
- Set the reverse records to `smtp` and `smtp2` if the server is used as a
mail server with Postfix, or else use `main` and `backup`.
- Add and use the `bind.generate_reverse` option as a boolean.
- Do not generate the reverse zones by default.
The idea is that the reverse zones are needed if the reverse management is delegated from the ISP or host (or LIR), but I don't think that's the most common case.
If it is to be generated and the server is used as a mail server, I guess the best practice would be to use the MX hostname as reverse DNS …
=> Dns reverse zones

tests/playbooks/dns-records-email.yml
We missed that one.
Check for "v=TLSRPTv1;[...]" content.
=> Fix TLS-RPT DNS record test

install/playbooks/roles/postfix/templates/master.cf, install/playbooks/roles/sogo/templates/sogo.conf
A commit to configure `smtpd_relay_restrictions` for submission ports in `master.cf` with only `mynetworks` and `sasl_authenticated`.
Another commit to use the `mail.postfix.submission.port` variable instead of the value `587` directly in `sogo.conf`.
=> Mail configuration

install/playbooks/roles/autoconfig/templates/config-v1.1.xml, install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/dovecot/templates/40-dovecot.bind, install/playbooks/roles/dovecot/templates/conf.d/10-master.conf, tests/playbooks/dns-records-email-pop3.yml, tests/playbooks/dns-records-email.yml
This change does the necessary to keep only the TLS ports open with Dovecot (imaps, pop3s), and closes the ports using STARTTLS (imap, pop3).
Using this will consider that all email clients used with the server will be able to use TLS (without STARTTLS). Some providers appear to do this by default, too (eg Gmail, Fastmail). Fastmail has a good write-up on this: https://www.fastmail.com/help/technical/ssltlsstarttls.html.
The auto{config,discover} configurations already announce the imaps port only (and pop3s if enabled).
What is your opinion on such a change?
Keep the `imap` listener on port `143` for the needs of the webmails
through `imapproxy` on localhost.
Disable the `pop3` listener on port 110, even if `mail.pop3` is enabled.
Close the firewall ports for `imap` and `pop3`.
Announce …
=> Use only TLS ports with Dovecot

install/playbooks/roles/ejabberd/templates/ejabberd.yml
Use a yaml form `"mail": "%u@{{ network.domain}}"` instead of what seems
to be an erlang config format `"mail", "%u@{{ network.domain }}"`.
Use an expanded list to avoid confusion between a yaml list of objects
and the similar erlang format `[{...}]`.
The ldap auth information was somehow found, but this change avoids
error messages like:
```
ignoring option 'ldap_uids' with invalid value: '[{"mail","%u@[...]
```
=> Fix ejabberd ldap_uids config option

install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/ejabberd/tasks/main.yml, install/playbooks/roles/ldap/tasks/main.yml, install/playbooks/roles/nginx/tasks/main.yml, install/playbooks/roles/postfix/tasks/main.yml
The acl's for the certificate directories should also apply to the subdirectories. Apparently this is implicitly applied on Debian Stretch, but on Debian Buster it is not. 
I think it is caused by:
[Debian Changelog:](https://metadata.ftp-master.debian.org/changelogs//main/a/acl/acl_2.2.53-4_changelog)
acl (2.2.53-1) unstable; urgency=medium
[...]
* Enable all hardening build flags.
I omitted acl for /etc/letsencrypt since access to the files in this directory does not seem to be necessary.
I tested the change on Debian Stretch and it does not seem to cause any problems.
=> make the acl for the certificate directories recursive

install/playbooks/roles/ejabberd/files/renewal-hook.sh
A follow up on #241.
Set the default ejabberd certificate from the main domain certificate
(`$DOMAIN` from `/etc/homebox/main.cf`). The `xmpp` subdomain is handled
by `nginx` and the `00-base.sh` renewal hook. The `conference` subdomain
handling is unchanged.
The renewal hooks are called once per certificate. a certficate can
contain several `$RENEWED_DOMAINS`. In homebox, the different domains
used by ejabberd are getting separate certificates, so the renewal hook
will be called for either one or the other, not both at the same time.
Use the `$RENEWED_LINEAGE` variable to get the live directory path for
the current certificate.
Do not change `/etc/ejabberd/*.pem` ownership and permissions from what
has been set by the ansible role tasks (`root:ejabberd`, `440`).
=> Fixes for the ejabberd renewal hook

install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/30-postfix.bind
Use the `ip4` and `ip6` mechanisms to avoid DNS queries for servers
checking the SPF record.
This is done under the assumption that the IP addresses are static, and
will not be renumbered without an update of the SPF record.
https://tools.ietf.org/html/rfc7208#section-10.1.1
=> Use IP addresses in the SPF record

.gitignore
Not sure why it was not generated before, but now with python 3.7.5 and ansible 2.8.3, I have a `__pycache__` directory is generated in `common/connection-plugins` for the `ssh_fwknop.py` script on any ansible-playbook call.
=> Let git ignore python3 cache directories

common/roles/external-ip-type/tasks/main.yml, install/playbooks/ejabberd.yml, install/playbooks/roles/system-prepare/meta/main.yml, install/playbooks/roles/system-prepare/tasks/main.yml
Following the discussion in #243, I modified the changes about `backup_ip` and `backup_ip_type` accordingly and refactored the two commits concerning `system-prepare`. Details are in the commit messages.
After those changes, I guess some sanity checks on the IP addresses could be included either in the `load-defaults` role or in the `external-ip-type` role. It might allow to be more confident in the that the `external_ip` and `backup_ip` are actually IP addresses in the playbooks and templates (instead of either undefined, None, the empty string, a random string or an IP address :sweat_smile:).
=> Some fixes following 231 and 238 v2

common/roles/external-ip-type/tasks/main.yml
Fix for the commit 759e673 merged with #252.
The jinja expression needs to be enclosed in braces (`{{…}}`) to be
evaluated.
Remove the multiline operator as it returned a quoted string instead of
getting the boolean value, and the enclosed jinja expression can be
split on several lines.
=> Fix the determination of the ipv6_used fact

common/roles/cert-perms/tasks/main.yml, install/playbooks/roles/certificates/files/renewal-hook.sh, install/playbooks/roles/certificates/tasks/main.yml, install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext, install/playbooks/roles/ldap/tasks/main.yml, install/playbooks/roles/ldap/vars/main.yml, install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/system-post-install/tasks/partitions-security.yml, tests/playbooks/roles/dev-support/tasks/main.yml
The certificates should be readable only by their counterparts
programs, for instance, imap / pop3 by dovecot, smtp by postfix,
etc...
This should fix #259
=> WiP: An attept to reduce the certificate permissions

install/playbooks/roles/dns-server-bind/tasks/main.yml
Add or remove the configuration file for the extra records before the bind forward zone configuration is assembled. Allow for reconfiguration if adding or removing records.
=> bind: extra records

install/playbooks/roles/dns-server-bind/templates/named.conf.options
From bind 9.11, the option `minimal-any` is available to reduce the size
of the ANY responses over UDP, and limit the possibility of traffic
amplification.
With `minimal-any yes`, Bind returns a single record (the first one it
can find) for ANY requests over UDP. TCP responses are unfiltered.
This behavior is described in RFC8482, 4.1:
https://tools.ietf.org/html/rfc8482#section-4.1
The `dig` command uses TCP by default for ANY requests, so be sure to
test with the option `+notcp`.
=> bind: use minimal ANY responses

install/playbooks/roles/backup-server/tasks/main.yml
`dir://` and `ssh://` cannot be mounted, so cannot be in `/mnt/backup`.
Limit access rights on directories.
=> User backup locations

git-hooks/pre-commit
An attempt at a pre-commit hook:
- use the git check for whitespace and leftover merge conflct markers from the sample pre-commit hook;
- add ansible-lint checks for the modified ansible YAML files in the index to be committed.
=> Pre-commit hook

install/playbooks/roles/dovecot/templates/apparmor.d/usr.lib.dovecot.script-login
Calls to `su` in the `dovecot-postlogin` script called by `script login`
try to access the files in the `/etc/security/limits.d/` folder.
Allow access to those files in the apparmor profile for `script-login`.
=> dovecot: script-login access to security limits

git-hooks/pre-push, tests/playbooks/roles/https-grade/tasks/main.yml, uninstall/playbooks/roles/transmission/tasks/main.yml
Address a warning in the https-grade playbook.
Lint the uninstall playbooks.
=> Ansible-lint more errors and warnings

install/playbooks/roles/ldap/vars/main.yml
This removed all the apparmor errors in the logs, like
"var/cache/nscd/...". Same bug on buster.
=> Replace nscd by unscd

install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/named.conf.options
bind9 support the option "minimal-any" only starting with minor version 11.
=> Fixed an error when IPv6 is not used

install/playbooks/mta-sts.yml, install/playbooks/roles/autoconfig/tasks/main.yml, install/playbooks/roles/autodiscover/tasks/main.yml, install/playbooks/roles/certificates/tasks/main.yml, install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/gogs/tasks/main.yml, install/playbooks/roles/ldap/tasks/main.yml, install/playbooks/roles/mta-sts/tasks/main.yml, install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/roundcube/tasks/main.yml, install/playbooks/roles/rspamd-web/tasks/main.yml, install/playbooks/roles/sogo/tasks/main.yml, install/playbooks/roles/transmission/tasks/main.yml, install/playbooks/roles/website-simple/tasks/main.yml, install/playbooks/roles/well-known-services/tasks/main.yml, install/playbooks/roles/zabbix-server/tasks/main.yml, install/playbooks/zabbix.yml
Set `wwww-data` access to the certificates using the `cert-perms` role
in each playbook needing it.
Use `import_role` to call the `cert-perms` role.
=> cert-perms: set www-data access per playbook

install/playbooks/roles/opendmarc/templates/20-dmarc.bind
This is necessary when the domain name is long and generate a record
longer than 255 characters.
=> Split DMARC text records on multiple lines

common/roles/external-ip-type/tasks/main.yml, install/playbooks/roles/borg-backup/tasks/restore-all.yml, install/playbooks/roles/certificates/tasks/gencert.yml, install/playbooks/roles/dns-server-bind-refresh/tasks/main.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-check-propagation/tasks/main.yml, install/playbooks/roles/postfix/tasks/main.yml, tests/playbooks/roles/tor/tasks/main.yml
Address ansible-lint E602 error "Don't compare to empty string" with the
test `| length > 0`.
The filter `| bool` gives the boolean value `True` only if the string is
one of `"true"`, `"True"`, `"yes"`, `"1"`, or other strings meaning
`True`. Any other non-empty string is translated to `False`.
The current recommended solution, to use the bare variable, gives
deprecation warnings now.
After reading the related discussions, this might be the current best
workaround:
https://github.com/ansible/ansible-lint/issues/457
https://stackoverflow.com/a/59085721
Keep legitimate uses of `| bool` in access-check scripts.
=> Use the length filter to test a non-empty string

install/playbooks/roles/sogo/tasks/main.yml
Allow for the configuration of sieve filters through the SOGo user
interface. If the `sogo.sieve` file is absent, SOGo fails to add the
rules as sieve filters.
SOGo seems to correctly create the file when configuring vacation
filters. Having both (configured filters, and then activate vacation
auto-responder) might give conflicts.
See:
https://lists.inverse.ca/sogo/arc/users/2016-06/msg00198.html
And for the full discussion:
https://lists.inverse.ca/sogo/arc/users/2017-05/msg00073.html
=> sogo: Create SOGo's sieve filter file

install/playbooks/roles/access-report/tasks/main.yml
Avoid messages like:
```
WARNING: Couldn't open /[…]/install/playbooks/roles/access-report/tasks/{'file': - No such file or directory
```
=> Fix ansible-lint warning on include_tasks

install/playbooks/roles/mta-sts/templates/nginx.conf, install/playbooks/roles/roundcube/templates/nginx.conf, install/playbooks/roles/rspamd-web/templates/nginx.conf
Some leftover from #294.
Remove the redundant and unused `ssl_protocols` nginx parameter from the
servers configurations. This parameter is defined in the global nginx
configuration (http) and takes precedence.
Modify mta-sts, roundcube and rspamd-web nginx configurations.
Could be applied on dev, but is really only a cleanup as the parameters ("TLSv1.1") are ignored.
=> TLS: remove ssl_protocols from nginx server confs

git-hooks/pre-push
Apply the same logic as the pre-commit hook of exporting in a temporary
directory the local branches, tags or commits being pushed. This allows
to run the ansible-lint checks on any branch without touching the state
of the working directory.
Loop over all the given references. Fail at the first error found.
Handle the case of remote branch deletion by not running ansible-lint.
Export all the files of the reference given by using `git archive`.
Other alternatives could have been: `git clone`, but is quite verbose
when not a proper branch, and the repository and origin configuration is
not needed ; `git worktree`, but requires a special case for the
currently checkout branch, and one wouldn't want to have dangling
worktrees if something goes very wrong.
Use `set -o pipefail`, so require …
=> git-hooks: pre-push improvements

install/playbooks/roles/borg-backup/files/backup.py
Keep the 'homebox-' prefix used at creation for compatibility with
existing backups.
Set the prefix as a backup self attribute.
Can also be merged to buster-dev.
=> borgbackup: fix the prefix for archive pruning

install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext
This change makes the aliases working on buster.
However, this configuration was not required on stretch. On buster, when the dovecot-lmtp gets the email for delivery, it considers it for the alias (eg log `dovecot: auth: Debug: master in: USER#0112#011ada.lovelace@[…]`) whereas on stretch it considers it for the already resolved user (eg `ada@`). I cannot see in the logs before dovecot-lmtp takes over where it would be different. The postfix ldap-aliases seem to do the work and resolve the alias ok.
The `check-utf8-email.yml` in tests is sending to an alias.
If you think this shouldn't be needed and can find a better fix in the integration between postfix and dovecot, it would be welcome.
=> dovecot: Search intlMailAddr for aliases in LDAP

config/defaults.yml, install/playbooks/roles/autoconfig/templates/config-v1.1.xml, install/playbooks/roles/autodiscover/templates/autodiscover.xml, install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/30-postfix.bind, install/playbooks/roles/postfix/templates/fail2ban-noise-reduction.conf, install/playbooks/roles/postfix/templates/master.cf, tests/playbooks/dns-records-email-submission.yml, tests/playbooks/dns-records-email.yml, tests/playbooks/main.yml, tests/playbooks/roles/postfix/tasks/check-certificates.yml
This is about the submission port over TLS (465) now called the "submissions" service as defined and updated in RFC8314, recommending TLS over STARTTLS.
Please see the commit messages for more details.
=> Postfix submissions

git-hooks/pre-commit, git-hooks/pre-push
The second step for the hooks. Should help catch imports or includes of missing ansible files.
Please find some more details in the commit messages.
=> Git hooks: treating warnings as error

install/playbooks/roles/postfix/tasks/main.yml
This fix need to be applied on Debian Stretch as the service is
unknown and postfix fails to start
=> Ensure service submission<s> is known by the system

common/ansible.cfg, tests/playbooks/roles/postfix/tasks/check-extension-email.yml, tests/playbooks/roles/postfix/tasks/check-simple-email.yml, tests/playbooks/roles/postfix/tasks/check-utf8-email.yml
Tune some ansible parameters to try to execute faster, mainly:
- SSH pipelining: disabled by default in ansible because in conflict with sudoers configurations using the `requiretty` option, which is not the case in Debian by default ;
- Smart fact gathering policy, which uses the ansible cache plugin and so requires to change the generation of unique email subjects in the tests playbooks (and was quite something to debug).
Please find more details in the commit messages.
A bit more than 20% faster on the re-execution of the main install playbook of an already deployed server (so nothing much done, just connections to the server to check), the server being a VM on the same machine, so without any network latency.
=> Ansible tuning

install/main.yml
Ansible-lint doesn't seem to catch this and ansible-playbook just throws a warning.
=> fwknop: Fix role names

install/roles/dovecot/tasks/main.yml, install/roles/mta-sts/tasks/main.yml, install/roles/postfix/tasks/main.yml
Dovecot apparently still needs to access the LDAP fullchain certificates (not the private key) even in buster, due to its (open)ldap client configuration.
There was a `www-data` access remaining in mta-sts, and the user postfix doesn't seem to need access to the certificates or private key.
This is not everything, since there is still the issue with openldap. The ldap role (and the calls to cert-perms) seems to do what's needed, but running the main playbook the mask of the private key seems to be reset at some point (to 0, giving an `effective: ---` for the user openldap).
=> Cert perms

install/roles/certificates-all/templates/nginx-cert.conf
It is documented as the preferred way of doing it:
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites
=> nginx: Use return 301 to redirect requests

docs/email-configuration.md, install/main.yml, install/roles/openpgp-wkd/handlers/main.yml, install/roles/openpgp-wkd/tasks/create_wkd_files.yml, install/roles/openpgp-wkd/tasks/main.yml, install/roles/openpgp-wkd/templates/80-openpgpkey.bind, install/roles/openpgp-wkd/templates/apparmor.d/local/openpgpkey, install/roles/openpgp-wkd/templates/nginx.conf, install/roles/openpgp-wkd/vars/main.yml
This PR requires #355 first, and addresses #336.
Use both the direct and advanced publishing methods.
- The direct method uses the well-known directory of the base domain.
Some PGP clients might only support this version.
- The advanced method uses an `openpgpkey` subdomain.
https://tools.ietf.org/html/draft-koch-openpgp-webkey-service
The public keys are expected to be in the server configuration in a
"pgp" object list along with the user's uid.
```
pgp:
- uid: marie
ascii_armored_public_key: |
-----BEGIN PGP PUBLIC KEY BLOCK-----
[…]
-----END PGP PUBLIC KEY BLOCK-----
```
The server's `gpg` is used to determine the WKD hash for each key, which
is then used to name the published files.
=> Add an OpenPGP Web Key Directory role

install/roles/well-known-services/templates/nginx.conf
Add a location for the `/.well-known/` URL prefix to serve the directory
for the base `{{ network.domain }}` on HTTPS.
=> well-known-services: serve well-known dir on HTTPS

roles/bootstrap/defaults/main.yml, roles/bootstrap/tasks/check/packages.yml, roles/bootstrap/tasks/install/packages.yml, roles/certificates/vars/main.yml
Due to role ordering in 'config/defaults/version-*.yml' it will always absent, as 'firewall' runs before 'certificates'.
=> Move 'colorize' package to 'bootstrap' role
