progmaticltd/homebox

.gitignore, README.md, install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.anvil, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.bounce, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.cleanup, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.discard, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.error, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.flush, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.lmtp, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.local, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.master, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.nqmgr, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.oqmgr, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.pickup, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.pipe, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.proxymap, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.qmgr, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.qmqpd, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.scache, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.showq, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.smtp, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.smtpd, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.spawn, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.tlsmgr, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.trivial-rewrite, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.verify, install/playbooks/roles/postfix/templates/apparmor.d/usr.lib.postfix.virtual
Postfix / AppArmor implementation
=> Updated postfix AppArmor configuration

install/playbooks/roles/postfix/tasks/main.yml, install/playbooks/roles/postfix/templates/apparmor.d/usr.sbin.postdrop, install/playbooks/roles/postfix/templates/apparmor.d/usr.sbin.sendmail
=> Updated AppArmpor postfix profile

install/playbooks/roles/autodiscover/tasks/main.yml, install/playbooks/roles/certificates/tasks/main.yml, install/playbooks/roles/certificates/templates/certificates-renew.sh, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/gogs/handlers/main.yml, install/playbooks/roles/gogs/tasks/main.yml, install/playbooks/roles/load-defaults/tasks/main.yml, install/playbooks/roles/opendkim/tasks/main.yml, install/playbooks/roles/roundcube/tasks/main.yml, install/playbooks/roles/system-prepare/tasks/main.yml
Create DNSSEC backup directory if it does not exists
Wehn creating or requesting a certificate, run the certificate check
script only for the required domain.
AppArmor and nginx handlers optimisation.
Create SSHFP records only when using DNSSEC
=> Various fixes, improvements and optimisations

README.md, config/defaults.yml, docs/tor-privoxy-configuration.md, install/playbooks/main.yml, install/playbooks/privoxy.yml, install/playbooks/roles/load-defaults/tasks/main.yml, install/playbooks/roles/privoxy/handlers/main.yml, install/playbooks/roles/privoxy/meta/main.yml, install/playbooks/roles/privoxy/tasks/main.yml, install/playbooks/roles/privoxy/templates/apparmor-privoxy, install/playbooks/roles/privoxy/templates/privoxy-config, install/playbooks/roles/tor/tasks/main.yml, install/playbooks/tor.yml, mkdocs.yml
A minimal but working tor configuration
=> Added Tor and Privoxy, plus documentation

config/defaults.yml, install/playbooks/main.yml, install/playbooks/roles/dns-server-bind/tasks/build-ip-info.yml, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/forward-head, install/playbooks/roles/dns-server-bind/templates/named.conf.local, install/playbooks/roles/dns-server-bind/templates/reverse-domain, install/playbooks/roles/dns-server-check-propagation/tasks/main.yml, install/playbooks/roles/dovecot/templates/40-dovecot.bind, install/playbooks/roles/external-ip/tasks/main.yml, install/playbooks/roles/ldap/tasks/main.yml, install/playbooks/roles/luks-remote/tasks/main.yml, install/playbooks/roles/luks-remote/tasks/set-dropbear.yml, install/playbooks/roles/postfix/templates/30-postfix.bind, install/playbooks/roles/system-prepare/tasks/main.yml, install/playbooks/roles/system-prepare/templates/sshfp.bind
=> Latest development branch from andre

README.md, docs/features.md, install/playbooks/roles/dns-server-bind/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/named.conf.options, install/playbooks/roles/roundcube/templates/config.inc.php, install/playbooks/roles/sogo/templates/50-sogo.bind
Minor documentation update about IPv6 support
=> Minor documentation update

install/playbooks/roles/dovecot/tasks/main.yml, install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.lib.dovecot.auth, install/playbooks/roles/dovecot/templates/apparmor.d/usr.lib.dovecot.indexer-worker, install/playbooks/roles/dovecot/templates/conf.d/10-master.conf, install/playbooks/roles/dovecot/templates/conf.d/15-mailboxes.conf, install/playbooks/roles/website-simple/tasks/main.yml, install/playbooks/website-simple.yml, tests/playbooks/roles/dev-cleanup/tasks/main.yml
- Better debug options for Dovecot.
- Fixed virtual folders issues with Dovecot
- Set default root shell before development files clean up
- Synchronize the simple web site content during the deployment
=> Development improvments and bug fixes

README.md, common/roles/load-defaults/tasks/main.yml, config/defaults.yml, docs/features.md, install/playbooks/hugo.yml, install/playbooks/roles/certificates/templates/renewal-hook.sh, install/playbooks/roles/hugo/handlers/main.yml, install/playbooks/roles/hugo/tasks/main.yml, install/playbooks/roles/hugo/templates/apparmor.d/local/hugo-web.cf, install/playbooks/roles/hugo/templates/apparmor.d/usr.bin.hugo, install/playbooks/roles/hugo/templates/config.toml, install/playbooks/roles/hugo/templates/hugo-server.service, install/playbooks/roles/hugo/templates/nginx.conf, install/playbooks/roles/import-accounts/files/import-emails
=> Website hugo

config/defaults.yml, install/playbooks/roles/dovecot/templates/conf.d/10-auth.conf, install/playbooks/roles/dovecot/templates/conf.d/15-lda.conf, install/playbooks/roles/dovecot/templates/conf.d/90-sieve.conf, install/playbooks/roles/dovecot/templates/sieve/before-global.sieve, install/playbooks/roles/packages/meta/main.yml, install/playbooks/roles/packages/tasks/main.yml, install/playbooks/roles/postfix/templates/ldap-aliases.cf, install/playbooks/roles/postfix/templates/main.cf, install/playbooks/roles/postfix/templates/senders-bcc.cf, uninstall/playbooks/ejabberd.yml, uninstall/playbooks/roles/certificates/meta/main.yml, uninstall/playbooks/roles/certificates/tasks/main.yml, uninstall/playbooks/roles/ejabberd/handlers/main.yml, uninstall/playbooks/roles/ejabberd/tasks/main.yml, uninstall/playbooks/roles/roundcube/handlers/main.yml, uninstall/playbooks/roles/roundcube/tasks/main.yml, uninstall/playbooks/roundcube.yml
- Apticron for new updates alerts
- LDAP and Sieve improvements
- Uninstallation playbooks for eJabberd and roundcube
- Uninstallation of certificates
- Allow login in dovecot authentication scheme
=> Improvements and fixes

config/defaults.yml, install/playbooks/roles/privoxy/files/update-rules.sh, install/playbooks/roles/privoxy/tasks/add-adblock-rules.yml, install/playbooks/roles/privoxy/tasks/main.yml, install/playbooks/roles/privoxy/templates/apparmor-privoxy-update-rules.cf, install/playbooks/roles/privoxy/templates/update-rules.cron
Add AppArmor profile for the script
=> privoxy adblock rules import improvement and some comments update in defaults.yml about DNSSEC

preseed/build.sh, preseed/playbooks/roles/build-iso/templates/build-mirror.sh
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928703
=> Fixed simple-cdd issue related to expired Wheezy certificate

config/defaults.yml, docs/configuration.md, docs/security-configuration.md, install/playbooks/roles/system-cleanup/handlers/main.yml, mkdocs.yml
Added documentation for clarity on ssh / sudo remote access scheme.
=> Ssh sudo changes

docs/external-accounts.md, docs/maintenance.md, install/playbooks/roles/dovecot/tasks/access-check.yml, install/playbooks/roles/ldap-email-updates/tasks/main.yml, install/playbooks/update-users.yml, tests/playbooks/main.yml
Amended the update-users playbook
Amended ldap-email-updates role
Updated some documentation
Skip dovecot FTS tests when fts is not installed
=> Maintenance and tests updates

install/playbooks/roles/system-cleanup/tasks/cleanup-common.yml, install/playbooks/roles/system-cleanup/tasks/main.yml, install/playbooks/roles/system-cleanup/tasks/network-bind.yml, install/playbooks/roles/system-cleanup/templates/dhclient.conf, install/playbooks/roles/system-cleanup/templates/homebox-dhclient-hook.sh, install/playbooks/roles/system-cleanup/templates/resolv.conf
- Cleanup packages cache
- Make sure resolv.conf is not overwritten when using bind
=> Post installation tasks cleanup

README.md, install/playbooks/roles/luks-remote/defaults/main.yml, install/playbooks/roles/luks-remote/handlers/main.yml, install/playbooks/roles/luks-remote/tasks/set-dropbear.yml, preseed/.gitignore, preseed/config/system-vultr-example.yml
Added links to ISO image building CI status
=> Continuous Integration improvements

preseed/build.sh
Use the group ID from the docker image (1000) and g+w permissions.
=> Fixed permission in the temporary folder shared with docker

README.md, common/roles/display-config/tasks/main.yml, common/roles/load-defaults/tasks/main.yml, config/defaults.yml, docs/installation.md, install/playbooks/display-config.yml, install/playbooks/load-defaults.yml, install/playbooks/roles/backup-server/meta/main.yml, install/playbooks/roles/backup-server/tasks/main.yml, install/playbooks/roles/dns-server-bind/templates/named.conf.options, install/playbooks/roles/ldap/tasks/main.yml
- Generate random password for users when not specified.
- Better and faster default settings loading and merging
- Added load default as a dependency for the backup server
- Minor modifications in bind and documentation
=> generate random password for users, simpler defaults loading and merging

config/defaults.yml, install/playbooks/main.yml
Also use ‘_’ for the flag name
=> Set propagation checking to false by default,

README.md, docs/installation.md, install/playbooks/roles/sogo/templates/apparmor.d/usr.sbin.sogo-backup
- Added mailing lists links
- Added missing AppArmor rules for SOGo backup
- Small update in the documentation
=> Documentation and small fixes

config/defaults.yml, install/playbooks/main.yml, install/playbooks/mta-sts.yml, install/playbooks/roles/mta-sts/handlers/main.yml, install/playbooks/roles/mta-sts/tasks/main.yml, install/playbooks/roles/mta-sts/templates/35-mta-sts.bind, install/playbooks/roles/mta-sts/templates/apparmor.d/local/mta-sts, install/playbooks/roles/mta-sts/templates/index.html, install/playbooks/roles/mta-sts/templates/mta-sts.txt, install/playbooks/roles/mta-sts/templates/nginx.conf
closes #110
Implement MTA-STS standard.
=> Implemented MTA-STS (RFC 8461)

install/playbooks/roles/dns-server-bind/templates/forward-head
A minor fix to some warning about wrong tag for CAA records.
=> Fixed an issue with tag string for CAA records

install/playbooks/roles/postfix/templates/30-postfix.bind, tests/playbooks/dns-records-email.yml
This should validate MTA-STS and TLS-RPT in the unit tests.
=> Added unit tests to test mta-sts and smtp-rpt

tests/playbooks/dns-records-autoconfig.yml, tests/playbooks/dns-records-autodiscover.yml, tests/playbooks/dns-records-dnssec.yml, tests/playbooks/dns-records-email.yml, tests/playbooks/dns-records-jabber-c2s.yml, tests/playbooks/dns-records-jabber-s2s.yml, tests/playbooks/dns-records-sshfp.yml, tests/playbooks/roles/dns-records/tasks/main.yml
Allow to check for the value of the records too, not only their presence.
=> Improve DNS tests

tests/playbooks/dns-records-email-pop3.yml, tests/playbooks/dns-records-email.yml, tests/playbooks/main.yml
=> Made pop3 dns tests optionals

install/playbooks/roles/ldap/tasks/main.yml, tests/playbooks/roles/ldap/tasks/main.yml
=> Make users shells configurable

install/playbooks/roles/certificates/templates/nginx-cert.conf, install/playbooks/roles/well-known-services/tasks/main.yml, install/playbooks/roles/well-known-services/templates/catchall.conf
Change to redirection for certificates servers, and addition of a default catchall server. Please see the commit messages for details.
=> Nginx configuration

install/playbooks/roles/import-accounts/files/import-emails, install/playbooks/roles/import-accounts/tasks/isync-template.yml, install/playbooks/roles/import-accounts/tasks/main.yml
Please see the commit messages.
=> import accounts logs and dependencies

install/playbooks/update-users.yml
At least, the CI is working and shout when someone (me) commit code without checking everything ;-)
=> Fixed reference to a non existing playbook

install/playbooks/roles/dovecot/files/dovecot-postlogin
Changes in the way `dovecot-postlogin` calls the login scripts.
=> Dovecot postlogin

.gitignore
I merged too fast the previous one, I will do this one
=> Added missing exception for defaults.yml in .gitignore.

common/roles/external-ip-type/tasks/main.yml, git-hooks/pre-push
=> Ansible-lint common roles

install/playbooks/roles/autodiscover/templates/autodiscover.xml
According to the current webmail / sogo installed, return the
appropriate sections.
=> Updated the autodiscover xml file

config/defaults.yml, install/playbooks/roles/ldap/handlers/main.yml, install/playbooks/roles/ldap/vars/main.yml, install/playbooks/roles/postfix/templates/headers-check.cf
My mistake about unscd.
BTW, I filled a bug report on debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945888
=> Unscd fixes

config/defaults.yml, install/playbooks/roles/postfix/templates/headers-check.cf
Allow to remove more headers when sending emails outside
=> Postfix: Remove some headers when sending emails

uninstall/playbooks/roles/zabbix-server/defaults/main.yml, uninstall/playbooks/roles/zabbix-server/handlers/main.yml, uninstall/playbooks/roles/zabbix-server/tasks/main.yml, uninstall/playbooks/zabbix-server.yml
Implemented a playbook to uninstall Zabbix
=> Implemented Zabbix uninstallation

README.md, docs/access-reports.md, install/playbooks/roles/access-report/files/access-report.py, install/playbooks/roles/access-report/files/apparmor.cf, install/playbooks/roles/access-report/tasks/cron-tasks.yml, install/playbooks/roles/access-report/tasks/main.yml
Update ISP afterall, before sending the report
Allow per week access
=> Improvements on the access report

install/playbooks/roles/backup-server/tasks/main.yml, install/playbooks/roles/clamav/tasks/main.yml, install/playbooks/roles/clamav/vars/main.yml, install/playbooks/roles/dns-server-check-propagation/meta/main.yml, install/playbooks/roles/ldap/tasks/main.yml, install/playbooks/roles/ldap/templates/indexes.ldif, install/playbooks/roles/ldap/vars/main.yml, install/playbooks/roles/postfix/templates/main.cf, install/playbooks/roles/system-post-install/templates/dhclient.conf, install/playbooks/roles/system-prepare/handlers/main.yml, install/playbooks/roles/system-prepare/tasks/main.yml
Almost the same fixes as the dev branch, except the small git repository server, which is a new feature.
=> Fixes for master

config/defaults.yml, install/playbooks/roles/dovecot/templates/apparmor.d/usr.local.bin.decode2text, install/playbooks/roles/dovecot/templates/conf.d/10-ssl.conf, tests/playbooks/roles/autoconfig/tasks/main.yml
A couple of changes needed, in addition of the `buster-updates` branch, to work towards a pass of the test suite.
The `Check if the email is in the sent folder` task in the `check_simple_email.yml` test doesn't seem to pass here: can't figure out why.
Some changes in the ejabberd configuration file are also needed, but haven't tested it yet (so not present in this PR).
=> Buster support

jenkins/mkdocs.Jenkinsfile
Added a simple pipeline for Jenkins and mkdocs
=> Added a Jenkinsfiles for mkdocs

README.md, jenkins/ansible-lint.Jenkinsfile
- Added ansible-lint Jenkins files
- Added CI status in the main readme
=> Readme ci status

README.md, jenkins/ansible-lint.Jenkinsfile, jenkins/mkdocs.Jenkinsfile
Added CI integration status for the master branch
=> Added CI status information from dev

docs/security-configuration.md
=> Document ssh access with private key only

install/playbooks/roles/dovecot/files/access-check-country.sh, install/playbooks/roles/dovecot/files/dovecot-postlogin
- Fix: Add SOURCE environment variable only once
- Fix: Correctly read ALLOW_EXTERNAL_QUERIES variable
- Quote values in tests to be consistent
=> Fixed minor issues in the dovecot post-login script

git-hooks/pre-commit
Adapt to the directory structure change, include some directories, and simplify the pattern list.
=> Update for the pre-commit hook

install/roles/certificates-all/vars/main.yml
That should complete the set of certificates.
=> certificates-all: Add missing certificates

install/roles/postfix/tasks/main.yml
=> Fix issue #342: smtpd_flags variable not set

docs/preseed.md
As I read the documentation I wondered where the preseed folder ist. Obviously it's in the repository so I added a step to clone the repo. I think this makes it easier for people who are new to git,linux,shell,...
=> Add instructions to clone the homebox repository

install/roles/clamav/tasks/main.yml, install/roles/remote-access/tasks/ufw-public-access.yml
Addresses #353 based on PR from #350 and comments.
=> Fix install issues bis

roles/grafana/tasks/install/config.yml
=> fix path for api-key with password store
